<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| If this is not set then CodeIgniter will guess the protocol, domain and
| path to your installation.
|
*/
$config['base_url']	= 'http://localhost/survey/';

/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = ''; 

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'AUTO' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'AUTO'			Default - auto detects
| 'PATH_INFO'		Uses the PATH_INFO
| 'QUERY_STRING'	Uses the QUERY_STRING
| 'REQUEST_URI'		Uses the REQUEST_URI
| 'ORIG_PATH_INFO'	Uses the ORIG_PATH_INFO
|
*/
$config['uri_protocol']	= 'AUTO';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/urls.html
*/

$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'vietnamese';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = FALSE;


/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/core_classes.html
| http://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';


/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify with a regular expression which characters are permitted
| within your URLs.  When someone tries to submit a URL with disallowed
| characters they will get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';


/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['allow_get_array']		= TRUE;
$config['enable_query_strings'] = FALSE;
$config['controller_trigger']	= 'c';
$config['function_trigger']		= 'm';
$config['directory_trigger']	= 'd'; // experimental not currently in use

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| If you have enabled error logging, you can set an error threshold to
| determine what gets logged. Threshold options are:
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 0;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ folder. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/cache/ folder.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class or the Session class you
| MUST set an encryption key.  See the user guide for info.
|
*/
$config['encryption_key'] = 'qwerty68265';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_cookie_name'		= the name you want for the cookie
| 'sess_expiration'			= the number of SECONDS you want the session to last.
|   by default sessions last 7200 seconds (two hours).  Set to zero for no expiration.
| 'sess_expire_on_close'	= Whether to cause the session to expire automatically
|   when the browser window is closed
| 'sess_encrypt_cookie'		= Whether to encrypt the cookie
| 'sess_use_database'		= Whether to save the session data to a database
| 'sess_table_name'			= The name of the session database table
| 'sess_match_ip'			= Whether to match the user's IP address when reading the session data
| 'sess_match_useragent'	= Whether to match the User Agent when reading the session data
| 'sess_time_to_update'		= how many seconds between CI refreshing Session Information
|
*/
$config['sess_cookie_name']		= 'ci_session';
$config['sess_expiration']		= 7200;
$config['sess_expire_on_close']	= FALSE;
$config['sess_encrypt_cookie']	= FALSE;
$config['sess_use_database']	= FALSE;
$config['sess_table_name']		= 'ci_sessions';
$config['sess_match_ip']		= FALSE;
$config['sess_match_useragent']	= TRUE;
$config['sess_time_to_update']	= 300;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix' = Set a prefix if you need to avoid collisions
| 'cookie_domain' = Set to .your-domain.com for site-wide cookies
| 'cookie_path'   =  Typically will be a forward slash
| 'cookie_secure' =  Cookies will only be set if a secure HTTPS connection exists.
|
*/
$config['cookie_prefix']	= "";
$config['cookie_domain']	= "";
$config['cookie_path']		= "/";
$config['cookie_secure']	= FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
*/
$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or 'gmt'.  This pref tells the system whether to use
| your server's local time as the master 'now' reference, or convert it to
| GMT.  See the 'date helper' page of the user guide for information
| regarding date handling.
|
*/
$config['time_reference'] = 'local';


/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
*/
$config['rewrite_short_tags'] = FALSE;


/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy IP
| addresses from which CodeIgniter should trust the HTTP_X_FORWARDED_FOR
| header in order to properly identify the visitor's IP address.
| Comma-delimited, e.g. '10.0.1.200,10.0.1.201'
|
*/
$config['proxy_ips'] = '';


/*
|--------------------------------------------------------------------------
| Avatar default data
|--------------------------------------------------------------------------
|
|
|
*/
$config['avatar_default'] = '<img alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAACXBIWXMAAAsTAAALEwEAmpwYAAAKT2lDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjanVNnVFPpFj333vRCS4iAlEtvUhUIIFJCi4AUkSYqIQkQSoghodkVUcERRUUEG8igiAOOjoCMFVEsDIoK2AfkIaKOg6OIisr74Xuja9a89+bN/rXXPues852zzwfACAyWSDNRNYAMqUIeEeCDx8TG4eQuQIEKJHAAEAizZCFz/SMBAPh+PDwrIsAHvgABeNMLCADATZvAMByH/w/qQplcAYCEAcB0kThLCIAUAEB6jkKmAEBGAYCdmCZTAKAEAGDLY2LjAFAtAGAnf+bTAICd+Jl7AQBblCEVAaCRACATZYhEAGg7AKzPVopFAFgwABRmS8Q5ANgtADBJV2ZIALC3AMDOEAuyAAgMADBRiIUpAAR7AGDIIyN4AISZABRG8lc88SuuEOcqAAB4mbI8uSQ5RYFbCC1xB1dXLh4ozkkXKxQ2YQJhmkAuwnmZGTKBNA/g88wAAKCRFRHgg/P9eM4Ors7ONo62Dl8t6r8G/yJiYuP+5c+rcEAAAOF0ftH+LC+zGoA7BoBt/qIl7gRoXgugdfeLZrIPQLUAoOnaV/Nw+H48PEWhkLnZ2eXk5NhKxEJbYcpXff5nwl/AV/1s+X48/Pf14L7iJIEyXYFHBPjgwsz0TKUcz5IJhGLc5o9H/LcL//wd0yLESWK5WCoU41EScY5EmozzMqUiiUKSKcUl0v9k4t8s+wM+3zUAsGo+AXuRLahdYwP2SycQWHTA4vcAAPK7b8HUKAgDgGiD4c93/+8//UegJQCAZkmScQAAXkQkLlTKsz/HCAAARKCBKrBBG/TBGCzABhzBBdzBC/xgNoRCJMTCQhBCCmSAHHJgKayCQiiGzbAdKmAv1EAdNMBRaIaTcA4uwlW4Dj1wD/phCJ7BKLyBCQRByAgTYSHaiAFiilgjjggXmYX4IcFIBBKLJCDJiBRRIkuRNUgxUopUIFVIHfI9cgI5h1xGupE7yAAygvyGvEcxlIGyUT3UDLVDuag3GoRGogvQZHQxmo8WoJvQcrQaPYw2oefQq2gP2o8+Q8cwwOgYBzPEbDAuxsNCsTgsCZNjy7EirAyrxhqwVqwDu4n1Y8+xdwQSgUXACTYEd0IgYR5BSFhMWE7YSKggHCQ0EdoJNwkDhFHCJyKTqEu0JroR+cQYYjIxh1hILCPWEo8TLxB7iEPENyQSiUMyJ7mQAkmxpFTSEtJG0m5SI+ksqZs0SBojk8naZGuyBzmULCAryIXkneTD5DPkG+Qh8lsKnWJAcaT4U+IoUspqShnlEOU05QZlmDJBVaOaUt2ooVQRNY9aQq2htlKvUYeoEzR1mjnNgxZJS6WtopXTGmgXaPdpr+h0uhHdlR5Ol9BX0svpR+iX6AP0dwwNhhWDx4hnKBmbGAcYZxl3GK+YTKYZ04sZx1QwNzHrmOeZD5lvVVgqtip8FZHKCpVKlSaVGyovVKmqpqreqgtV81XLVI+pXlN9rkZVM1PjqQnUlqtVqp1Q61MbU2epO6iHqmeob1Q/pH5Z/YkGWcNMw09DpFGgsV/jvMYgC2MZs3gsIWsNq4Z1gTXEJrHN2Xx2KruY/R27iz2qqaE5QzNKM1ezUvOUZj8H45hx+Jx0TgnnKKeX836K3hTvKeIpG6Y0TLkxZVxrqpaXllirSKtRq0frvTau7aedpr1Fu1n7gQ5Bx0onXCdHZ4/OBZ3nU9lT3acKpxZNPTr1ri6qa6UbobtEd79up+6Ynr5egJ5Mb6feeb3n+hx9L/1U/W36p/VHDFgGswwkBtsMzhg8xTVxbzwdL8fb8VFDXcNAQ6VhlWGX4YSRudE8o9VGjUYPjGnGXOMk423GbcajJgYmISZLTepN7ppSTbmmKaY7TDtMx83MzaLN1pk1mz0x1zLnm+eb15vft2BaeFostqi2uGVJsuRaplnutrxuhVo5WaVYVVpds0atna0l1rutu6cRp7lOk06rntZnw7Dxtsm2qbcZsOXYBtuutm22fWFnYhdnt8Wuw+6TvZN9un2N/T0HDYfZDqsdWh1+c7RyFDpWOt6azpzuP33F9JbpL2dYzxDP2DPjthPLKcRpnVOb00dnF2e5c4PziIuJS4LLLpc+Lpsbxt3IveRKdPVxXeF60vWdm7Obwu2o26/uNu5p7ofcn8w0nymeWTNz0MPIQ+BR5dE/C5+VMGvfrH5PQ0+BZ7XnIy9jL5FXrdewt6V3qvdh7xc+9j5yn+M+4zw33jLeWV/MN8C3yLfLT8Nvnl+F30N/I/9k/3r/0QCngCUBZwOJgUGBWwL7+Hp8Ib+OPzrbZfay2e1BjKC5QRVBj4KtguXBrSFoyOyQrSH355jOkc5pDoVQfujW0Adh5mGLw34MJ4WHhVeGP45wiFga0TGXNXfR3ENz30T6RJZE3ptnMU85ry1KNSo+qi5qPNo3ujS6P8YuZlnM1VidWElsSxw5LiquNm5svt/87fOH4p3iC+N7F5gvyF1weaHOwvSFpxapLhIsOpZATIhOOJTwQRAqqBaMJfITdyWOCnnCHcJnIi/RNtGI2ENcKh5O8kgqTXqS7JG8NXkkxTOlLOW5hCepkLxMDUzdmzqeFpp2IG0yPTq9MYOSkZBxQqohTZO2Z+pn5mZ2y6xlhbL+xW6Lty8elQfJa7OQrAVZLQq2QqboVFoo1yoHsmdlV2a/zYnKOZarnivN7cyzytuQN5zvn//tEsIS4ZK2pYZLVy0dWOa9rGo5sjxxedsK4xUFK4ZWBqw8uIq2Km3VT6vtV5eufr0mek1rgV7ByoLBtQFr6wtVCuWFfevc1+1dT1gvWd+1YfqGnRs+FYmKrhTbF5cVf9go3HjlG4dvyr+Z3JS0qavEuWTPZtJm6ebeLZ5bDpaql+aXDm4N2dq0Dd9WtO319kXbL5fNKNu7g7ZDuaO/PLi8ZafJzs07P1SkVPRU+lQ27tLdtWHX+G7R7ht7vPY07NXbW7z3/T7JvttVAVVN1WbVZftJ+7P3P66Jqun4lvttXa1ObXHtxwPSA/0HIw6217nU1R3SPVRSj9Yr60cOxx++/p3vdy0NNg1VjZzG4iNwRHnk6fcJ3/ceDTradox7rOEH0x92HWcdL2pCmvKaRptTmvtbYlu6T8w+0dbq3nr8R9sfD5w0PFl5SvNUyWna6YLTk2fyz4ydlZ19fi753GDborZ752PO32oPb++6EHTh0kX/i+c7vDvOXPK4dPKy2+UTV7hXmq86X23qdOo8/pPTT8e7nLuarrlca7nuer21e2b36RueN87d9L158Rb/1tWeOT3dvfN6b/fF9/XfFt1+cif9zsu72Xcn7q28T7xf9EDtQdlD3YfVP1v+3Njv3H9qwHeg89HcR/cGhYPP/pH1jw9DBY+Zj8uGDYbrnjg+OTniP3L96fynQ89kzyaeF/6i/suuFxYvfvjV69fO0ZjRoZfyl5O/bXyl/erA6xmv28bCxh6+yXgzMV70VvvtwXfcdx3vo98PT+R8IH8o/2j5sfVT0Kf7kxmTk/8EA5jz/GMzLdsAAAAgY0hSTQAAeiUAAICDAAD5/wAAgOkAAHUwAADqYAAAOpgAABdvkl/FRgAAEapJREFUeNrsnXuw3VV1xz9r/X7n3kB4JDwSwrPlJSAFpM7wKgIWaQsFecUZOgJCa0BBwtSqg4z8oRUGsIqYQLVoaZCHbYqlVRjGaZGgxRZssVAKShlQsbwUDQSSe89vf/vH3ud1c4O55573/a3MLzm5j3P2b6/vXuu71m/vtUwSpcxd8XIKSgCUUgKglBIApcxJydv5pbN/8EbfBmyAG7gZZhHBZoYBZvH7EL9X+3mDxcAhwKEY+wK7AQuASnrbSeCXwE8QPwT+A3hE8EKNIkeuLJRex39FSP8PEiF9vVdyy8Fb9AcAQyK7AH8InC74bWD7qMnN/v2fA98H7gS+ATxXWoDhkAOBiyTeA2w3ixW5PXBCun4B/C2wEnis5ACDKUuAGwQPCV0otJ3o2J/t4nvyEHBj+qwSAAMk5woeDuIDQcwLgi5d84K4UPAwcG7pAvov8wWflbSsx5+7M3AzcCTwp8C60gL0XnYV3CtYpsTt+nAtE9wL7FpagN7K7oJ7EAcMwJOMo4gg+APgxyUAup8I2EFwl6QDBmhUBwB3YbwL8XIJgO7JuMTXFJM6gyaHAF8DTgQ2jDQAAn0zvFcbvHOA5/OdgmuA5aMNgNAX03+iwfIh2L1wieBexN2lBeicbI24fohc1fXAA8CrIwmAPmwiuhTYa4gAsFca86dG0wL0FgGLhsmnNsly4IvAiyMIgJ76/vOoPckbLtkeOA9x9QhygN6FfQTOZ3jlfIzrBjksHHQXcCSw7xADYF/EkcB9pQtoT05h+OWUEQRATxDgwDEjAIBj0r2E0gLMTHYB3jICAHhLupeflBZgpv4TthwBAGwJ7DNaAOjN2PZkdGQv4F9KCzAz2XWEADCw9zLIHGDBCAFgwYgBoCcIGB8hAIyXFmBgqcbcvpdBtgCvjRAAXh0tAPRmbC+OEABeGi0A9MYHPDNCAHimtAAzlx+ljxr200sh3UtJAmcoT4F+NgL5gJ+BPVWSwJnLOuIZvGEHwMOgdaUFaE/uBp063Pq3gd4dPOgbQu5O4eBWQ6r910AjCIDeje+5BIL3DCkA7mbAK4sMw67gLwwxAL4w6AMchnMB3yGevv29IVP+vWnslBZg9vIJwfEG2TBoXlAYfGIYxjr45wKiPATcGODioeD9cGOqJzSiAOjP6eDLEcdj7Dfgy/8JGZd37e0FBTDZoVU4LGcDAdYC50h8m8HdK/i6wTmItZ180yDYEMREEPNzZ7sx4ze3rMwpDlDzrQ8By4CvDigAlgEPWSeUDqwvxKRgYcV5+8IKhy4Y44TF4xy4TYWFY95HC9DfSb41iO2Bzw+Y8pe7cets52ciiDcKsaDiHLn9OL+/eJzjF81j3627U8xlWItEXS9RpDjb+jwWAR8yY+Vs3mR9IaqCveZnnLzzFizdZQsO2KbS9cEPc53AlQG9AHwJWNinMbwCLHNs9WwUPyk4ZNsKF+45n5OWzGPrvHdPwPsHAOuIX1kt8aTgL4kHSXsp/2pwoRmPzvjWDTYUYkOIir9gz/mcscsWjHnvjVl7HKBDIUjzu7gZlibALH1PqUD7m3/co8BxQpcgLgO265pTiOP4BcZVhl0PTPw6RddK19fLzQs2VMWeW+VcsvdWfVP8rADwyovr259Di5PQpGEk8AzcIwjySkZecbLcyHPHM6PeAEDTAmJC8BngTsFyxDl0fi/+L4FVFsnn07YJhZtZHKJEtSqq1YLqZKBaBIpUcPj1Nwr+7PAdOWu3/kezPbcAdQCEptUtmCziCwEKk3FC3XCPIKiMZ4yNZ1TGMjyPgLCmVZXkaWC5xOeA9wJnAgfPco5+AKwGvmrWtLcvNacwNwxDITCxITAxEZiYKKhWRShCbCIhYR5/x4nmYCIMRr2zgeEA1vy3NxZ5URVFtcr6N6pxhSVAjM3LyOfleG6Ye919YIB4RuLPgatAbxd6h8Q7iL0EFgObarXxBvAC8JgZawxbA/YwUFgyQqYE0kJMFqKoBqoTBRMbqhRFBKNFZODWsAq11iXGYIm10zdwy5v+tyMuoNkCKKm8yTNMSw6jhQjxRQKEZdFdeOZYZrGFTB7/BUVwRIDMSwBYBGyT/n/QFOX/GPhper3+tRden0pWWt1Q/Ij4GbWve7JOxjQ/l8at2petvu3VrMGBLKHF2ohzXzt/ryGwALNBbaM5UOzXMxkoJqdwgxpnQBEQEQDriX2BXiT2CxoDnkg/OEnch/g6xgZBYA401RyJljE1tj1lqewA7Af2Voz9Je2D2Q4YO2BsmwCQ03iuUKOmAZhEvAa8DDwJ/Dux8OMT6WslAAZQ5hG7gp2A2bEYb8Vth9RWjFpbsbphsI2IiIEM4UAusQXSjoj9kU4lAEHrEU8B9wD/QOwutr4EQH/lKIyluJ2E2964RT9bZ2Awpafc9IRUrYCwuk1QU4cIzSPoQAUOJOgjBP0fQV8HbgO+WwKgd7IdxpmYnW+ZHYYbliUyNVXx01HvX8eqNNUw1JhpfG2qNRFiiQp9kKAPUugRYkOp1cQuYyUAuiA7YlyA2wXkviuZNRh+i6lv0nI7cZdNG7400JGAgIRF14CCDqHQF6mGTyJWEMvEvlQCoDMyH+Mi3JZbZjuTO/VVb1MVPzUK6HDeQs2vE/AkTDE3QO6LqYZPUehigj5L7DU4sCeDhuHg5Rm4PUjFr2Y829nGM6ziMQGUpctjfG1mjavZ9Xfiqr9f02fUPjeNw3PDKo6NZzCeLabiV+P2PeCMEgAzzhixG3CrVXy1jftv2ViGVzwmeDKDltU/Zfkb7WVQfp0FsGkCh2aE1ACZWxzrWIaN+4FW8dXArcSexaUL2IzJPssy+wvLfQm5QebgtKZ72yF33XAHzS5HxBRfzTU4kGWQBSyzP1I1HEfQh4HbSwuwaV9/g1X8NhvPljDm0aTmTf5+o/CuC6u9HavQ7HM8pXGTNbCKw5hj49kSq/htwA3A/NICtMo+uN3iuR1GxaM5dZ+iYOvtSp8VUWx6EOCRM8gDuGPGB1TVoQSdTZ+LRwyKBTjeMv+2jWWH2ViO5RmeZfFBjxtmjuEYNYI34H/qY/Q49nQfnmVYnmFjOTaWHZblvma/BWOnrfvjvcfmLgCM91Lxb9p4trNVHPJNJHVqPtWG5GoZbyNXYZnFe6w4Gst2enJddfWSv/7hh4/bZsLmogtYbrlfV1M8aaUMhblv1y1YfDqpGkjM/dXJ/Mr71vobFruLzAEAxGTKRyz3ayx3rJbY8SkJnGFX/lQgqBG9xE0vBnl9Y8DnqKoCXDv6ADA+arldHVe+N1Z9M5sfJeVvBIL033r62lMUGa5RVUbsPjqyALjQK0n5aQdP3U+OquKnzVWk+1ZyCSQQWLhaVa0lbnUfUAC0o6Ro9pda7iut4liWQr03e2o36kBofq6QNZvAsJKqfg783egAwDjCMrvZKu6typ8jK3+TIKjt/RPKYugocBFuVqGfAg8OHADa0NVuuN1hFd/S8obybS4rfyNLEDeVymLeA9gShTsI+h262G7Ge3B/88ztdq/47p5Fwuel8qddUWZpbjzucPaK725utxO3uw2OBZjJSSYZ11rFjqrl81tCvVL501oCc8UQMV5HaVLXGvahAeIAm6M5AbbUc7u4Jdafi4SvHWJoYOa1jUcXq6o13SCFXQwDbVdzX2FNZ/tK5W8+MTRLfCBzggxCWKEQHiQeWukzCbTN+qEVXrFFlltJ+tpFgkcQxF1ntihM2grg1E4SN28fpm9ymb3Pc3u35VaSvg6RQssNz+3dwPsGnQQuJrOrvCnFa6Oc3u0VH3BDuYPCVRS6h3h2sV8uwDZJ/GT2ac9tp7hR0stkTweQYMkVQMBlOwXxaRN/MoB5ADvCMzvPM8fjzpfGDl0bnkf5A3NZ805kcPeYH8jsPOCI/lmATfuGKz0zNy9JX6ddQdxDIHDDM/MQuBJ0nPUDANMq1Djdczu27vt9493apcySD3isG5C4wLGhqtOBOwchDKyY2xWeNR2YsFLzHceBGfK47dwzg2BXKOifiLUN+koCz/DMD7Ys1vRpebxb4qBzovr+EQKGBz84KJwB3NFbF7Dx6r8sKj8e4PDS93ctNwBGcOE4IQtYsMsU9PftWoH28gCtAzvRMjvIs5i0wKarvVBKJ7lAbZ6JbuAgSScCd/XOBXjLxs1LPZn+Ft9fAqCbmQHkiiXnMiMEuxS1B4DZ5gEO98yOcS939/TcFdRzA4ZndgxweO9cQOOQ5vs9c4t1+srV33Nv4KSIAEPh/Wb2vZ5YgHTUaZG7nxbNf6r1S5nx62WG0C3NfSTgpxHrH3YfAO7gzlLPWOi1uL9Ufn/SxGnxecZCd5a698IFZA5wlmWNyhyl2e+PHzAZyoSbocLOyjJf2XUAZJm/DeNwq53XL6W/IEhH0WUcjngb8J/dtQC57c10TRxLLPQ8M9hQipEaa+49EwB4m6i7k6BrVKR6eamYoqn0zT27GsUrY5m6qItrsJk9HGo3FVxI+pgKjctseSQiDZ9EuQOouys+VVc3xRZ+CoD0ecv9Yz3JAzQN6FKC1hHs48qmlD4vtd8lDCQUBIuNOwpAuhJvr1vprB8GSVxO0GvAlbWmD/HwhzA1ijOr1N2sEn9qWvWqVScthAp9HOeqdt+/Q+cCdJUKvRRkKz23MaNW6aNx/LUMFtpeYPW1H5UvFESoakJBF4HdNJv3zzuFU0k3Uei5IFaRs4NTe2gUz7/XTEC5T2Rmio8lBFJzrSBCIUJVLyvoHIx7Zvs5eUdtVeAeBR2nKrdIHGIZ6dx7c7xaAmGzFG8NxSOgqJv8RxTLyz3Wic/r7K7gqNTHQtCxRVWrQlWomkKUWsiSjj3Wbmyubxqq33/TfNR76aUC1KqKUBVFVatC0LGdUn5nLUCr/Arp3FDVA5Jdk2W+EGoPkRJBbNo1YnPZIqiprmRqgVcjekpEryjCKyr0UWx2/r77FmDje7tJhY4uqsV9oRpQEWLoEqg3XqinDOZaIknNncNSE4paP8UgVARCNVBUi/tU6Gjgpm7oqBdFov5bBSeEoIsJXOGBhZ6RCirblNVvrfkjG73V3hoSq1YnCskaDL8QodArodAnJVZgVLs1pB5VCrUqcF0odEQxGVYXk4FQVd0iKNRjiVadj5BFaCkPl+4Vmk19nJNiMlBMhtWh0BHAddA95fcQAHV5UmJpqOrkYrJ4uAUIRT2lmYAwPVkcSsWroXRLBE8hEbwWxRcPh6pOBpYS29V1XfpVKvYbCnyrkM5RKC6V+wGexQbStRgoHi3bOHkw8O5hipk3a8R2qpH7BIBk6gkhPB4C1yFWARt6Odx+1greAPxVKLhNRThHhV0cMjsgS3WE3C3RhOmOmNtGueW+bEXfZGd71QlejHyNkEheSH6+iDH94yFohWAV1p++QoPQL2Ad4sYQ9DcEnanClnlmRwVPx5+sUVK1YQjUGjZOE0Nadxd4I7nVmq9tvJy62hVXeyJ53w1BXyK2mHu9n5M/SA0jXgdWhaBVIegYM852t1M8sx29Vm/fG0elNRUQmzQH6gAc1BShtC57NZv9lOyqKT4kghei0l8KQf8ocYu73T8okz6YPYPE/RL3F0E7hUInmXGaZ3a0uW3jXjuEojoYmmNJm7JWrZZkmLWp17Smv56nb17tSekKejUUWiPxdYlvmvP8oE31oPcNfF7iyxJfDkF7mOl3zexd7hxhZnuYN59IagaEbcwJmtjj5jUO1cakrqb4plWulLWr+XZJz4XAA5K+JfHP7jw7yBM8TJ1Dn0V8RdJXisA2oEPMOMzMDjfjYHPb3YxKc3EKayGP1sizz8TfT8fga49lRaGg5yW+L+k7Ev8GPGJua4dlUoe1d/BaYI3EmmSC54P2wNjfYH+MPc34DTNbDCwyY2vMKvX9Sjate58+lJOCxASwVtKLEj9CPCr4L8T/AM96ZuuGdB5HpH28sQ7xOPB4nYjBOLAt0k6YLYCwNbAjsACopCunUWtHiYiuJbZ6fQF4GuwFpJcwex70K3PbwAiJSeVmrbksXk5BCYBSSgCUUgKglDkp/z8AkRyLASeVcREAAAAASUVORK5CYII=" />';
/* End of file config.php */
/* Location: ./application/config/config.php */
